name: Test and Deploy
run-name: ${{ github.actor }} is attempting to deploy to the cloud.
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.13'
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          cd pipeline
          python -m pip install --upgrade pip
          pip install -e .
      - name: Test
        run: pytest -x
  lint:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.13'
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          cd pipeline
          python -m pip install --upgrade pip
          pip install -e .
      - name: Lint
        run: |
          cd pipeline
          pylint src/museum_pipeline/*.py --fail-under 8
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    environment: myenvironment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            pipeline/src
            pipeline/pyproject.toml
      - name: Deploy to ec2
        if: ${{ success() }}
        uses: easingthemes/ssh-deploy@main 
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
  deploy:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd museum-pipeline/pipeline
            mkdir logs
            python3.13 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -e .
            pkill -15 python3.13
            nohup python3.13 src/museum_pipeline/lms_kafka_pipeline.py -store >> logs/pipeline.jsonl 2>&1 &
            nohup python3.13 src/museum_pipeline/lmnh_kafka_pipeline.py -store >> logs/pipeline.jsonl 2>&1 &
